# Generated by Django 3.0.5 on 2020-05-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubApp', '0002_event_meetingminute_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meetagenda',
            new_name='meetingagenda',
        ),
    ]
